package com.ziksana.domain.assessment;

import java.util.Date;

public class AssignmentTest {

	/**
	 * This field corresponds to the database column
	 * asmassignmenttest.AssignmentTestId
	 */
	private Integer assignmentTestId;
	/**
	 * This field corresponds to the database column asmassignmenttest.Active
	 */
	private Boolean active;
	/**
	 * This field corresponds to the database column
	 * asmassignmenttest.UsageStartDate
	 */
	private Date usageStartDate;
	/**
	 * This field corresponds to the database column
	 * asmassignmenttest.UsageEndDate
	 */
	private Date usageEndDate;
	/**
	 * This field corresponds to the database column asmassignmenttest.Name
	 */
	private String name;
	/**
	 * This field corresponds to the database column asmassignmenttest.TestType
	 */
	private Integer testType;
	/**
	 * This field corresponds to the database column
	 * asmassignmenttest.AssignmentContent
	 */
	private String assignmentContent;
	/**
	 * This field corresponds to the database column
	 * asmassignmenttest.DificultyLevel
	 */
	private Integer dificultyLevel;
	/**
	 * This field corresponds to the database column
	 * asmassignmenttest.Instruction
	 */
	private String instruction;
	/**
	 * This field corresponds to the database column
	 * asmassignmenttest.ZeniCreatedIndicator
	 */
	private Boolean zeniCreatedIndicator;
	/**
	 * This field corresponds to the database column
	 * asmassignmenttest.LearnerCreatedIndicator
	 */
	private Boolean learnerCreatedIndicator;
	/**
	 * This field corresponds to the database column
	 * asmassignmenttest.MultipleAttemptsAllowedIndicator
	 */
	private Boolean multipleAttemptsAllowedIndicator;
	/**
	 * This field corresponds to the database column
	 * asmassignmenttest.OpenforPeerEvaluationIndicator
	 */
	private Boolean openforPeerEvaluationIndicator;
	/**
	 * This field corresponds to the database column
	 * asmassignmenttest.AsynchronousIndicator
	 */
	private Boolean asynchronousIndicator;
	/**
	 * This field corresponds to the database column
	 * asmassignmenttest.ProctoringNeededIndicator
	 */
	private Boolean proctoringNeededIndicator;
	/**
	 * This field corresponds to the database column
	 * asmassignmenttest.AnswerWithinTime
	 */
	private Integer answerWithinTime;
	/**
	 * This field corresponds to the database column asmassignmenttest.Status
	 */
	private Integer status;
	/**
	 * This field corresponds to the database column
	 * asmassignmenttest.LearningComponentId
	 */
	private Integer learningComponentId;
	/**
	 * This field corresponds to the database column
	 * asmassignmenttest.MemberRoleId
	 */
	private Integer memberRoleId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column asmassignmenttest.AssignmentTestId
	 * 
	 * @return the value of asmassignmenttest.AssignmentTestId
	 */
	public Integer getAssignmentTestId() {
		return assignmentTestId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column asmassignmenttest.AssignmentTestId
	 * 
	 * @param assignmentTestId
	 *            the value for asmassignmenttest.AssignmentTestId
	 */
	public void setAssignmentTestId(Integer assignmentTestId) {
		this.assignmentTestId = assignmentTestId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column asmassignmenttest.Active
	 * 
	 * @return the value of asmassignmenttest.Active
	 */
	public Boolean getActive() {
		return active;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column asmassignmenttest.Active
	 * 
	 * @param active
	 *            the value for asmassignmenttest.Active
	 */
	public void setActive(Boolean active) {
		this.active = active;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column asmassignmenttest.UsageStartDate
	 * 
	 * @return the value of asmassignmenttest.UsageStartDate
	 */
	public Date getUsageStartDate() {
		return usageStartDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column asmassignmenttest.UsageStartDate
	 * 
	 * @param usageStartDate
	 *            the value for asmassignmenttest.UsageStartDate
	 */
	public void setUsageStartDate(Date usageStartDate) {
		this.usageStartDate = usageStartDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column asmassignmenttest.UsageEndDate
	 * 
	 * @return the value of asmassignmenttest.UsageEndDate
	 */
	public Date getUsageEndDate() {
		return usageEndDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column asmassignmenttest.UsageEndDate
	 * 
	 * @param usageEndDate
	 *            the value for asmassignmenttest.UsageEndDate
	 */
	public void setUsageEndDate(Date usageEndDate) {
		this.usageEndDate = usageEndDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column asmassignmenttest.Name
	 * 
	 * @return the value of asmassignmenttest.Name
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column asmassignmenttest.Name
	 * 
	 * @param name
	 *            the value for asmassignmenttest.Name
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column asmassignmenttest.TestType
	 * 
	 * @return the value of asmassignmenttest.TestType
	 */
	public Integer getTestType() {
		return testType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column asmassignmenttest.TestType
	 * 
	 * @param testType
	 *            the value for asmassignmenttest.TestType
	 */
	public void setTestType(Integer testType) {
		this.testType = testType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column asmassignmenttest.AssignmentContent
	 * 
	 * @return the value of asmassignmenttest.AssignmentContent
	 */
	public String getAssignmentContent() {
		return assignmentContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column asmassignmenttest.AssignmentContent
	 * 
	 * @param assignmentContent
	 *            the value for asmassignmenttest.AssignmentContent
	 */
	public void setAssignmentContent(String assignmentContent) {
		this.assignmentContent = assignmentContent == null ? null
				: assignmentContent.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column asmassignmenttest.DificultyLevel
	 * 
	 * @return the value of asmassignmenttest.DificultyLevel
	 */
	public Integer getDificultyLevel() {
		return dificultyLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column asmassignmenttest.DificultyLevel
	 * 
	 * @param dificultyLevel
	 *            the value for asmassignmenttest.DificultyLevel
	 */
	public void setDificultyLevel(Integer dificultyLevel) {
		this.dificultyLevel = dificultyLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column asmassignmenttest.Instruction
	 * 
	 * @return the value of asmassignmenttest.Instruction
	 */
	public String getInstruction() {
		return instruction;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column asmassignmenttest.Instruction
	 * 
	 * @param instruction
	 *            the value for asmassignmenttest.Instruction
	 */
	public void setInstruction(String instruction) {
		this.instruction = instruction == null ? null : instruction.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column asmassignmenttest.ZeniCreatedIndicator
	 * 
	 * @return the value of asmassignmenttest.ZeniCreatedIndicator
	 */
	public Boolean getZeniCreatedIndicator() {
		return zeniCreatedIndicator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column asmassignmenttest.ZeniCreatedIndicator
	 * 
	 * @param zeniCreatedIndicator
	 *            the value for asmassignmenttest.ZeniCreatedIndicator
	 */
	public void setZeniCreatedIndicator(Boolean zeniCreatedIndicator) {
		this.zeniCreatedIndicator = zeniCreatedIndicator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column asmassignmenttest.LearnerCreatedIndicator
	 * 
	 * @return the value of asmassignmenttest.LearnerCreatedIndicator
	 */
	public Boolean getLearnerCreatedIndicator() {
		return learnerCreatedIndicator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column asmassignmenttest.LearnerCreatedIndicator
	 * 
	 * @param learnerCreatedIndicator
	 *            the value for asmassignmenttest.LearnerCreatedIndicator
	 */
	public void setLearnerCreatedIndicator(Boolean learnerCreatedIndicator) {
		this.learnerCreatedIndicator = learnerCreatedIndicator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column
	 * asmassignmenttest.MultipleAttemptsAllowedIndicator
	 * 
	 * @return the value of asmassignmenttest.MultipleAttemptsAllowedIndicator
	 */
	public Boolean getMultipleAttemptsAllowedIndicator() {
		return multipleAttemptsAllowedIndicator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column
	 * asmassignmenttest.MultipleAttemptsAllowedIndicator
	 * 
	 * @param multipleAttemptsAllowedIndicator
	 *            the value for
	 *            asmassignmenttest.MultipleAttemptsAllowedIndicator
	 */
	public void setMultipleAttemptsAllowedIndicator(
			Boolean multipleAttemptsAllowedIndicator) {
		this.multipleAttemptsAllowedIndicator = multipleAttemptsAllowedIndicator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column
	 * asmassignmenttest.OpenforPeerEvaluationIndicator
	 * 
	 * @return the value of asmassignmenttest.OpenforPeerEvaluationIndicator
	 */
	public Boolean getOpenforPeerEvaluationIndicator() {
		return openforPeerEvaluationIndicator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column
	 * asmassignmenttest.OpenforPeerEvaluationIndicator
	 * 
	 * @param openforPeerEvaluationIndicator
	 *            the value for asmassignmenttest.OpenforPeerEvaluationIndicator
	 */
	public void setOpenforPeerEvaluationIndicator(
			Boolean openforPeerEvaluationIndicator) {
		this.openforPeerEvaluationIndicator = openforPeerEvaluationIndicator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column asmassignmenttest.AsynchronousIndicator
	 * 
	 * @return the value of asmassignmenttest.AsynchronousIndicator
	 */
	public Boolean getAsynchronousIndicator() {
		return asynchronousIndicator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column asmassignmenttest.AsynchronousIndicator
	 * 
	 * @param asynchronousIndicator
	 *            the value for asmassignmenttest.AsynchronousIndicator
	 */
	public void setAsynchronousIndicator(Boolean asynchronousIndicator) {
		this.asynchronousIndicator = asynchronousIndicator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column asmassignmenttest.ProctoringNeededIndicator
	 * 
	 * @return the value of asmassignmenttest.ProctoringNeededIndicator
	 */
	public Boolean getProctoringNeededIndicator() {
		return proctoringNeededIndicator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column asmassignmenttest.ProctoringNeededIndicator
	 * 
	 * @param proctoringNeededIndicator
	 *            the value for asmassignmenttest.ProctoringNeededIndicator
	 */
	public void setProctoringNeededIndicator(Boolean proctoringNeededIndicator) {
		this.proctoringNeededIndicator = proctoringNeededIndicator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column asmassignmenttest.AnswerWithinTime
	 * 
	 * @return the value of asmassignmenttest.AnswerWithinTime
	 */
	public Integer getAnswerWithinTime() {
		return answerWithinTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column asmassignmenttest.AnswerWithinTime
	 * 
	 * @param answerWithinTime
	 *            the value for asmassignmenttest.AnswerWithinTime
	 */
	public void setAnswerWithinTime(Integer answerWithinTime) {
		this.answerWithinTime = answerWithinTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column asmassignmenttest.Status
	 * 
	 * @return the value of asmassignmenttest.Status
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column asmassignmenttest.Status
	 * 
	 * @param status
	 *            the value for asmassignmenttest.Status
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column asmassignmenttest.LearningComponentId
	 * 
	 * @return the value of asmassignmenttest.LearningComponentId
	 */
	public Integer getLearningComponentId() {
		return learningComponentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column asmassignmenttest.LearningComponentId
	 * 
	 * @param learningComponentId
	 *            the value for asmassignmenttest.LearningComponentId
	 */
	public void setLearningComponentId(Integer learningComponentId) {
		this.learningComponentId = learningComponentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column asmassignmenttest.MemberRoleId
	 * 
	 * @return the value of asmassignmenttest.MemberRoleId
	 */
	public Integer getMemberRoleId() {
		return memberRoleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column asmassignmenttest.MemberRoleId
	 * 
	 * @param memberRoleId
	 *            the value for asmassignmenttest.MemberRoleId
	 */
	public void setMemberRoleId(Integer memberRoleId) {
		this.memberRoleId = memberRoleId;
	}
}