package com.ziksana.domain.assessment;

import java.util.Date;

public class QuestionBankAnswer {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column asmquestionbankanswer.QuestionBankAnswerId
	 */
	private Integer questionBankAnswerId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column asmquestionbankanswer.CreationDate
	 */
	private Date creationDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column asmquestionbankanswer.Active
	 */
	private Boolean active;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column asmquestionbankanswer.AnswerContent
	 */
	private String answerContent;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column asmquestionbankanswer.CorrectnessIndicator
	 */
	private Boolean correctnessIndicator;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column asmquestionbankanswer.AnswerSequence
	 */
	private Integer answerSequence;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column asmquestionbankanswer.AnswerReflectionComment
	 */
	private String answerReflectionComment;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column asmquestionbankanswer.AnswerKeywordWeight
	 */
	private Integer answerKeywordWeight;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column asmquestionbankanswer.Status
	 */
	private Integer status;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column asmquestionbankanswer.QuestionBankId
	 */
	private Integer questionBankId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column asmquestionbankanswer.MatchingQuestionBankAnswerId
	 */
	private Integer matchingQuestionBankAnswerId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column asmquestionbankanswer.VisualSpotId
	 */
	private Integer visualSpotId;

	/**
	 * This method returns the value of the database column
	 * asmquestionbankanswer.QuestionBankAnswerId
	 * 
	 * @return the value of asmquestionbankanswer.QuestionBankAnswerId
	 */
	public Integer getQuestionBankAnswerId() {
		return questionBankAnswerId;
	}

	/**
	 * This method sets the value of the database column
	 * asmquestionbankanswer.QuestionBankAnswerId
	 * 
	 * @param questionBankAnswerId
	 *            the value for asmquestionbankanswer.QuestionBankAnswerId
	 */
	public void setQuestionBankAnswerId(Integer questionBankAnswerId) {
		this.questionBankAnswerId = questionBankAnswerId;
	}

	/**
	 * This method returns the value of the database column
	 * asmquestionbankanswer.CreationDate
	 * 
	 * @return the value of asmquestionbankanswer.CreationDate
	 */
	public Date getCreationDate() {
		return creationDate;
	}

	/**
	 * This method sets the value of the database column
	 * asmquestionbankanswer.CreationDate
	 * 
	 * @param creationDate
	 *            the value for asmquestionbankanswer.CreationDate
	 */
	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	/**
	 * This method returns the value of the database column
	 * asmquestionbankanswer.Active
	 * 
	 * @return the value of asmquestionbankanswer.Active
	 */
	public Boolean getActive() {
		return active;
	}

	/**
	 * This method sets the value of the database column
	 * asmquestionbankanswer.Active
	 * 
	 * @param active
	 *            the value for asmquestionbankanswer.Active
	 */
	public void setActive(Boolean active) {
		this.active = active;
	}

	/**
	 * This method returns the value of the database column
	 * asmquestionbankanswer.AnswerContent
	 * 
	 * @return the value of asmquestionbankanswer.AnswerContent
	 */
	public String getAnswerContent() {
		return answerContent;
	}

	/**
	 * This method sets the value of the database column
	 * asmquestionbankanswer.AnswerContent
	 * 
	 * @param answerContent
	 *            the value for asmquestionbankanswer.AnswerContent
	 */
	public void setAnswerContent(String answerContent) {
		this.answerContent = answerContent == null ? null : answerContent
				.trim();
	}

	/**
	 * This method returns the value of the database column
	 * asmquestionbankanswer.CorrectnessIndicator
	 * 
	 * @return the value of asmquestionbankanswer.CorrectnessIndicator
	 */
	public Boolean getCorrectnessIndicator() {
		return correctnessIndicator;
	}

	/**
	 * This method sets the value of the database column
	 * asmquestionbankanswer.CorrectnessIndicator
	 * 
	 * @param correctnessIndicator
	 *            the value for asmquestionbankanswer.CorrectnessIndicator
	 */
	public void setCorrectnessIndicator(Boolean correctnessIndicator) {
		this.correctnessIndicator = correctnessIndicator;
	}

	/**
	 * This method returns the value of the database column
	 * asmquestionbankanswer.AnswerSequence
	 * 
	 * @return the value of asmquestionbankanswer.AnswerSequence
	 */
	public Integer getAnswerSequence() {
		return answerSequence;
	}

	/**
	 * This method sets the value of the database column
	 * asmquestionbankanswer.AnswerSequence
	 * 
	 * @param answerSequence
	 *            the value for asmquestionbankanswer.AnswerSequence
	 */
	public void setAnswerSequence(Integer answerSequence) {
		this.answerSequence = answerSequence;
	}

	/**
	 * This method returns the value of the database column
	 * asmquestionbankanswer.AnswerReflectionComment
	 * 
	 * @return the value of asmquestionbankanswer.AnswerReflectionComment
	 */
	public String getAnswerReflectionComment() {
		return answerReflectionComment;
	}

	/**
	 * This method sets the value of the database column
	 * asmquestionbankanswer.AnswerReflectionComment
	 * 
	 * @param answerReflectionComment
	 *            the value for asmquestionbankanswer.AnswerReflectionComment
	 */
	public void setAnswerReflectionComment(String answerReflectionComment) {
		this.answerReflectionComment = answerReflectionComment == null ? null
				: answerReflectionComment.trim();
	}

	/**
	 * This method returns the value of the database column
	 * asmquestionbankanswer.AnswerKeywordWeight
	 * 
	 * @return the value of asmquestionbankanswer.AnswerKeywordWeight
	 */
	public Integer getAnswerKeywordWeight() {
		return answerKeywordWeight;
	}

	/**
	 * This method sets the value of the database column
	 * asmquestionbankanswer.AnswerKeywordWeight
	 * 
	 * @param answerKeywordWeight
	 *            the value for asmquestionbankanswer.AnswerKeywordWeight
	 */
	public void setAnswerKeywordWeight(Integer answerKeywordWeight) {
		this.answerKeywordWeight = answerKeywordWeight;
	}

	/**
	 * This method returns the value of the database column
	 * asmquestionbankanswer.Status
	 * 
	 * @return the value of asmquestionbankanswer.Status
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method sets the value of the database column
	 * asmquestionbankanswer.Status
	 * 
	 * @param status
	 *            the value for asmquestionbankanswer.Status
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method returns the value of the database column
	 * asmquestionbankanswer.QuestionBankId
	 * 
	 * @return the value of asmquestionbankanswer.QuestionBankId
	 */
	public Integer getQuestionBankId() {
		return questionBankId;
	}

	/**
	 * This method sets the value of the database column
	 * asmquestionbankanswer.QuestionBankId
	 * 
	 * @param questionBankId
	 *            the value for asmquestionbankanswer.QuestionBankId
	 */
	public void setQuestionBankId(Integer questionBankId) {
		this.questionBankId = questionBankId;
	}

	/**
	 * This method returns the value of the database column
	 * asmquestionbankanswer.MatchingQuestionBankAnswerId
	 * 
	 * @return the value of asmquestionbankanswer.MatchingQuestionBankAnswerId
	 */
	public Integer getMatchingQuestionBankAnswerId() {
		return matchingQuestionBankAnswerId;
	}

	/**
	 * This method sets the value of the database column
	 * asmquestionbankanswer.MatchingQuestionBankAnswerId
	 * 
	 * @param matchingQuestionBankAnswerId
	 *            the value for
	 *            asmquestionbankanswer.MatchingQuestionBankAnswerId
	 */
	public void setMatchingQuestionBankAnswerId(
			Integer matchingQuestionBankAnswerId) {
		this.matchingQuestionBankAnswerId = matchingQuestionBankAnswerId;
	}

	/**
	 * This method returns the value of the database column
	 * asmquestionbankanswer.VisualSpotId
	 * 
	 * @return the value of asmquestionbankanswer.VisualSpotId
	 */
	public Integer getVisualSpotId() {
		return visualSpotId;
	}

	/**
	 * This method sets the value of the database column
	 * asmquestionbankanswer.VisualSpotId
	 * 
	 * @param visualSpotId
	 *            the value for asmquestionbankanswer.VisualSpotId
	 */
	public void setVisualSpotId(Integer visualSpotId) {
		this.visualSpotId = visualSpotId;
	}

}