package com.ziksana.domain.course.subscription;

import java.util.Date;

public class CourseActivity {
	/**
	 * This field corresponds to the database column sbncourseactivity.courseActivityId
	 * 
	 */
	private Integer courseActivityId;

	/**
	 * This field corresponds to the database column
	 * sbncourseactivity.ActivityDate
	 * 
	 */
	private Date activityDate;

	/**
	 * This field corresponds to the database column
	 * sbncourseactivity.ActivityType
	 * 
	 */
	private Integer activityType;

	/**
	 * This field corresponds to the database column sbncourseactivity.StartTime
	 * 
	 */
	private Date startTime;

	/**
	 * This field corresponds to the database column sbncourseactivity.EndTime
	 * 
	 */
	private Date endTime;

	/**
	 * This field corresponds to the database column
	 * sbncourseactivity.ZeniSuggestedIndicator
	 * 
	 */
	private Boolean zeniSuggestedIndicator;

	/**
	 * This field corresponds to the database column
	 * sbncourseactivity.FacilitationNeededIndicator
	 * 
	 */
	private Boolean facilitationNeededIndicator;

	/**
	 * This field corresponds to the database column
	 * sbncourseactivity.FacilitationCompletedIndicator
	 * 
	 */
	private Boolean facilitationCompletedIndicator;

	/**
	 * This field corresponds to the database column
	 * sbncourseactivity.FacilitationUsedIndicator
	 * 
	 */
	private Boolean facilitationUsedIndicator;

	/**
	 * This field corresponds to the database column
	 * sbncourseactivity.SubscriptionCourseId
	 * 
	 */
	private Integer subscriptionCourseId;

	/**
	 * This field corresponds to the database column
	 * sbncourseactivity.Description
	 * 
	 */
	private String description;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sbncourseactivity.courseActivityId
	 * 
	 * @return the value of sbncourseactivity.courseActivityId
	 * 
	 */
	public Integer getCourseActivityId() {
		return courseActivityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sbncourseactivity.courseActivityId
	 * 
	 * @param courseActivityId
	 *            the value for sbncourseactivity.courseActivityId
	 * 
	 */
	public void setCourseActivityId(Integer courseActivityId) {
		this.courseActivityId = courseActivityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sbncourseactivity.ActivityDate
	 * 
	 * @return the value of sbncourseactivity.ActivityDate
	 * 
	 */
	public Date getActivityDate() {
		return activityDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sbncourseactivity.ActivityDate
	 * 
	 * @param activityDate
	 *            the value for sbncourseactivity.ActivityDate
	 * 
	 */
	public void setActivityDate(Date activityDate) {
		this.activityDate = activityDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sbncourseactivity.ActivityType
	 * 
	 * @return the value of sbncourseactivity.ActivityType
	 * 
	 */
	public Integer getActivityType() {
		return activityType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sbncourseactivity.ActivityType
	 * 
	 * @param activityType
	 *            the value for sbncourseactivity.ActivityType
	 * 
	 */
	public void setActivityType(Integer activityType) {
		this.activityType = activityType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sbncourseactivity.StartTime
	 * 
	 * @return the value of sbncourseactivity.StartTime
	 * 
	 */
	public Date getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sbncourseactivity.StartTime
	 * 
	 * @param startTime
	 *            the value for sbncourseactivity.StartTime
	 * 
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sbncourseactivity.EndTime
	 * 
	 * @return the value of sbncourseactivity.EndTime
	 * 
	 */
	public Date getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sbncourseactivity.EndTime
	 * 
	 * @param endTime
	 *            the value for sbncourseactivity.EndTime
	 * 
	 */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sbncourseactivity.ZeniSuggestedIndicator
	 * 
	 * @return the value of sbncourseactivity.ZeniSuggestedIndicator
	 * 
	 */
	public Boolean getZeniSuggestedIndicator() {
		return zeniSuggestedIndicator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sbncourseactivity.ZeniSuggestedIndicator
	 * 
	 * @param zeniSuggestedIndicator
	 *            the value for sbncourseactivity.ZeniSuggestedIndicator
	 * 
	 */
	public void setZeniSuggestedIndicator(Boolean zeniSuggestedIndicator) {
		this.zeniSuggestedIndicator = zeniSuggestedIndicator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column
	 * sbncourseactivity.FacilitationNeededIndicator
	 * 
	 * @return the value of sbncourseactivity.FacilitationNeededIndicator
	 * 
	 */
	public Boolean getFacilitationNeededIndicator() {
		return facilitationNeededIndicator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column
	 * sbncourseactivity.FacilitationNeededIndicator
	 * 
	 * @param facilitationNeededIndicator
	 *            the value for sbncourseactivity.FacilitationNeededIndicator
	 * 
	 */
	public void setFacilitationNeededIndicator(
			Boolean facilitationNeededIndicator) {
		this.facilitationNeededIndicator = facilitationNeededIndicator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column
	 * sbncourseactivity.FacilitationCompletedIndicator
	 * 
	 * @return the value of sbncourseactivity.FacilitationCompletedIndicator
	 * 
	 */
	public Boolean getFacilitationCompletedIndicator() {
		return facilitationCompletedIndicator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column
	 * sbncourseactivity.FacilitationCompletedIndicator
	 * 
	 * @param facilitationCompletedIndicator
	 *            the value for sbncourseactivity.FacilitationCompletedIndicator
	 * 
	 */
	public void setFacilitationCompletedIndicator(
			Boolean facilitationCompletedIndicator) {
		this.facilitationCompletedIndicator = facilitationCompletedIndicator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sbncourseactivity.FacilitationUsedIndicator
	 * 
	 * @return the value of sbncourseactivity.FacilitationUsedIndicator
	 * 
	 */
	public Boolean getFacilitationUsedIndicator() {
		return facilitationUsedIndicator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sbncourseactivity.FacilitationUsedIndicator
	 * 
	 * @param facilitationUsedIndicator
	 *            the value for sbncourseactivity.FacilitationUsedIndicator
	 * 
	 */
	public void setFacilitationUsedIndicator(Boolean facilitationUsedIndicator) {
		this.facilitationUsedIndicator = facilitationUsedIndicator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sbncourseactivity.SubscriptionCourseId
	 * 
	 * @return the value of sbncourseactivity.SubscriptionCourseId
	 * 
	 */
	public Integer getSubscriptionCourseId() {
		return subscriptionCourseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sbncourseactivity.SubscriptionCourseId
	 * 
	 * @param subscriptionCourseId
	 *            the value for sbncourseactivity.SubscriptionCourseId
	 * 
	 */
	public void setSubscriptionCourseId(Integer subscriptionCourseId) {
		this.subscriptionCourseId = subscriptionCourseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sbncourseactivity.Description
	 * 
	 * @return the value of sbncourseactivity.Description
	 * 
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sbncourseactivity.Description
	 * 
	 * @param description
	 *            the value for sbncourseactivity.Description
	 * 
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}
}