package com.ziksana.domain.assessment.personality;

public class PersonalityCluster {

	/**
	 * This field corresponds to the database column pstcluster.ClusterId
	 */
	private Integer clusterId;
	/**
	 * This field corresponds to the database column pstcluster.Version
	 */
	private Integer version;
	/**
	 * This field corresponds to the database column pstcluster.Active
	 */
	private Boolean active;
	/**
	 * This field corresponds to the database column pstcluster.CategoryId
	 */
	private Integer categoryId;
	/**
	 * This field corresponds to the database column pstcluster.TestQuestionId
	 */
	private Integer testQuestionId;
	/**
	 * This field corresponds to the database column
	 * pstcluster.QuestionBankAnswerId
	 */
	private Integer questionBankAnswerId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pstcluster.ClusterId
	 * 
	 * @return the value of pstcluster.ClusterId
	 */
	public Integer getClusterId() {
		return clusterId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pstcluster.ClusterId
	 * 
	 * @param clusterId
	 *            the value for pstcluster.ClusterId
	 */
	public void setClusterId(Integer clusterId) {
		this.clusterId = clusterId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pstcluster.Version
	 * 
	 * @return the value of pstcluster.Version
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pstcluster.Version
	 * 
	 * @param version
	 *            the value for pstcluster.Version
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pstcluster.Active
	 * 
	 * @return the value of pstcluster.Active
	 */
	public Boolean getActive() {
		return active;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pstcluster.Active
	 * 
	 * @param active
	 *            the value for pstcluster.Active
	 */
	public void setActive(Boolean active) {
		this.active = active;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pstcluster.CategoryId
	 * 
	 * @return the value of pstcluster.CategoryId
	 */
	public Integer getCategoryId() {
		return categoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pstcluster.CategoryId
	 * 
	 * @param categoryId
	 *            the value for pstcluster.CategoryId
	 */
	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pstcluster.TestQuestionId
	 * 
	 * @return the value of pstcluster.TestQuestionId
	 */
	public Integer getTestQuestionId() {
		return testQuestionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pstcluster.TestQuestionId
	 * 
	 * @param testQuestionId
	 *            the value for pstcluster.TestQuestionId
	 */
	public void setTestQuestionId(Integer testQuestionId) {
		this.testQuestionId = testQuestionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pstcluster.QuestionBankAnswerId
	 * 
	 * @return the value of pstcluster.QuestionBankAnswerId
	 */
	public Integer getQuestionBankAnswerId() {
		return questionBankAnswerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pstcluster.QuestionBankAnswerId
	 * 
	 * @param questionBankAnswerId
	 *            the value for pstcluster.QuestionBankAnswerId
	 */
	public void setQuestionBankAnswerId(Integer questionBankAnswerId) {
		this.questionBankAnswerId = questionBankAnswerId;
	}
}