package com.ziksana.persistence.polls;

import com.ziksana.domain.polls.PollTracker;
import com.ziksana.domain.polls.PollTrackerExample;
import com.ziksana.domain.polls.PollTrackerKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PollTrackerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utlzpolltracker
     *
     * @mbggenerated Mon Sep 10 17:04:28 IST 2012
     */
    //int countByExample(PollTrackerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utlzpolltracker
     *
     * @mbggenerated Mon Sep 10 17:04:28 IST 2012
     */
    //int deleteByExample(PollTrackerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utlzpolltracker
     *
     * @mbggenerated Mon Sep 10 17:04:28 IST 2012
     */
    int deleteByPrimaryKey(PollTrackerKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utlzpolltracker
     *
     * @mbggenerated Mon Sep 10 17:04:28 IST 2012
     */
    int insert(PollTracker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utlzpolltracker
     *
     * @mbggenerated Mon Sep 10 17:04:28 IST 2012
     */
    int insertSelective(PollTracker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utlzpolltracker
     *
     * @mbggenerated Mon Sep 10 17:04:28 IST 2012
     */
    //List<PollTracker> selectByExample(PollTrackerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utlzpolltracker
     *
     * @mbggenerated Mon Sep 10 17:04:28 IST 2012
     */
    PollTracker selectByPrimaryKey(PollTrackerKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utlzpolltracker
     *
     * @mbggenerated Mon Sep 10 17:04:28 IST 2012
     */
    //int updateByExampleSelective(@Param("record") PollTracker record, @Param("example") PollTrackerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utlzpolltracker
     *
     * @mbggenerated Mon Sep 10 17:04:28 IST 2012
     */
    int updateByExample(@Param("record") PollTracker record, @Param("example") PollTrackerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utlzpolltracker
     *
     * @mbggenerated Mon Sep 10 17:04:28 IST 2012
     */
    int updateByPrimaryKeySelective(PollTracker record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utlzpolltracker
     *
     * @mbggenerated Mon Sep 10 17:04:28 IST 2012
     */
    int updateByPrimaryKey(PollTracker record);
}