package com.ziksana.persistence.polls;

import com.ziksana.domain.polls.Poll;
import com.ziksana.domain.polls.PollExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PollMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utlzpoll
     *
     * @mbggenerated Mon Sep 10 17:04:28 IST 2012
     */
    //int countByExample(PollExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utlzpoll
     *
     * @mbggenerated Mon Sep 10 17:04:28 IST 2012
     */
    //int deleteByExample(PollExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utlzpoll
     *
     * @mbggenerated Mon Sep 10 17:04:28 IST 2012
     */
    int deleteByPrimaryKey(Integer pollId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utlzpoll
     *
     * @mbggenerated Mon Sep 10 17:04:28 IST 2012
     */
    int insert(Poll record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utlzpoll
     *
     * @mbggenerated Mon Sep 10 17:04:28 IST 2012
     */
    int insertSelective(Poll record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utlzpoll
     *
     * @mbggenerated Mon Sep 10 17:04:28 IST 2012
     */
    //List<Poll> selectByExample(PollExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utlzpoll
     *
     * @mbggenerated Mon Sep 10 17:04:28 IST 2012
     */
    Poll selectByPrimaryKey(Integer pollId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utlzpoll
     *
     * @mbggenerated Mon Sep 10 17:04:28 IST 2012
     */
    //int updateByExampleSelective(@Param("record") Poll record, @Param("example") PollExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utlzpoll
     *
     * @mbggenerated Mon Sep 10 17:04:28 IST 2012
     */
    //int updateByExample(@Param("record") Poll record, @Param("example") PollExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utlzpoll
     *
     * @mbggenerated Mon Sep 10 17:04:28 IST 2012
     */
    int updateByPrimaryKeySelective(Poll record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utlzpoll
     *
     * @mbggenerated Mon Sep 10 17:04:28 IST 2012
     */
    int updateByPrimaryKey(Poll record);
}