package com.ziksana.domain.polls;

public class PollQuestionResponse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utlzpollquestionresponse.ID
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    private Integer ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utlzpollquestionresponse.Answer1Count
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    private Integer answer1Count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utlzpollquestionresponse.Answer2Count
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    private Integer answer2Count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utlzpollquestionresponse.Answer3Count
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    private Integer answer3Count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utlzpollquestionresponse.Answer4Count
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    private Integer answer4Count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utlzpollquestionresponse.Answer5Count
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    private Integer answer5Count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utlzpollquestionresponse.TotalRespondents
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    private Integer totalRespondents;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utlzpollquestionresponse.ID
     *
     * @return the value of utlzpollquestionresponse.ID
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    public Integer getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utlzpollquestionresponse.ID
     *
     * @param ID the value for utlzpollquestionresponse.ID
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    public void setID(Integer ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utlzpollquestionresponse.Answer1Count
     *
     * @return the value of utlzpollquestionresponse.Answer1Count
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    public Integer getAnswer1Count() {
        return answer1Count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utlzpollquestionresponse.Answer1Count
     *
     * @param answer1Count the value for utlzpollquestionresponse.Answer1Count
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    public void setAnswer1Count(Integer answer1Count) {
        this.answer1Count = answer1Count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utlzpollquestionresponse.Answer2Count
     *
     * @return the value of utlzpollquestionresponse.Answer2Count
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    public Integer getAnswer2Count() {
        return answer2Count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utlzpollquestionresponse.Answer2Count
     *
     * @param answer2Count the value for utlzpollquestionresponse.Answer2Count
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    public void setAnswer2Count(Integer answer2Count) {
        this.answer2Count = answer2Count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utlzpollquestionresponse.Answer3Count
     *
     * @return the value of utlzpollquestionresponse.Answer3Count
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    public Integer getAnswer3Count() {
        return answer3Count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utlzpollquestionresponse.Answer3Count
     *
     * @param answer3Count the value for utlzpollquestionresponse.Answer3Count
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    public void setAnswer3Count(Integer answer3Count) {
        this.answer3Count = answer3Count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utlzpollquestionresponse.Answer4Count
     *
     * @return the value of utlzpollquestionresponse.Answer4Count
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    public Integer getAnswer4Count() {
        return answer4Count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utlzpollquestionresponse.Answer4Count
     *
     * @param answer4Count the value for utlzpollquestionresponse.Answer4Count
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    public void setAnswer4Count(Integer answer4Count) {
        this.answer4Count = answer4Count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utlzpollquestionresponse.Answer5Count
     *
     * @return the value of utlzpollquestionresponse.Answer5Count
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    public Integer getAnswer5Count() {
        return answer5Count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utlzpollquestionresponse.Answer5Count
     *
     * @param answer5Count the value for utlzpollquestionresponse.Answer5Count
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    public void setAnswer5Count(Integer answer5Count) {
        this.answer5Count = answer5Count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utlzpollquestionresponse.TotalRespondents
     *
     * @return the value of utlzpollquestionresponse.TotalRespondents
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    public Integer getTotalRespondents() {
        return totalRespondents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utlzpollquestionresponse.TotalRespondents
     *
     * @param totalRespondents the value for utlzpollquestionresponse.TotalRespondents
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    public void setTotalRespondents(Integer totalRespondents) {
        this.totalRespondents = totalRespondents;
    }
}