package com.ziksana.domain.polls;

public class PollTrackerKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utlzpolltracker.MemberRoleId
     *
     * @mbggenerated Mon Sep 10 17:04:28 IST 2012
     */
    private Integer memberRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utlzpolltracker.PollId
     *
     * @mbggenerated Mon Sep 10 17:04:28 IST 2012
     */
    private Integer pollId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utlzpolltracker.MemberRoleId
     *
     * @return the value of utlzpolltracker.MemberRoleId
     *
     * @mbggenerated Mon Sep 10 17:04:28 IST 2012
     */
    public Integer getMemberRoleId() {
        return memberRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utlzpolltracker.MemberRoleId
     *
     * @param memberRoleId the value for utlzpolltracker.MemberRoleId
     *
     * @mbggenerated Mon Sep 10 17:04:28 IST 2012
     */
    public void setMemberRoleId(Integer memberRoleId) {
        this.memberRoleId = memberRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utlzpolltracker.PollId
     *
     * @return the value of utlzpolltracker.PollId
     *
     * @mbggenerated Mon Sep 10 17:04:28 IST 2012
     */
    public Integer getPollId() {
        return pollId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utlzpolltracker.PollId
     *
     * @param pollId the value for utlzpolltracker.PollId
     *
     * @mbggenerated Mon Sep 10 17:04:28 IST 2012
     */
    public void setPollId(Integer pollId) {
        this.pollId = pollId;
    }
}