package com.ziksana.domain.polls;

import com.ziksana.domain.polls.PollQuestionResponse;
import com.ziksana.domain.polls.PollQuestionResponseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PollQuestionResponseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utlzpollquestionresponse
     *
     * @mbggenerated Mon Sep 10 17:04:28 IST 2012
     */
    int countByExample(PollQuestionResponseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utlzpollquestionresponse
     *
     * @mbggenerated Mon Sep 10 17:04:28 IST 2012
     */
    int deleteByExample(PollQuestionResponseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utlzpollquestionresponse
     *
     * @mbggenerated Mon Sep 10 17:04:28 IST 2012
     */
    int deleteByPrimaryKey(Integer pollQuestionResponseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utlzpollquestionresponse
     *
     * @mbggenerated Mon Sep 10 17:04:28 IST 2012
     */
    int insert(PollQuestionResponse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utlzpollquestionresponse
     *
     * @mbggenerated Mon Sep 10 17:04:28 IST 2012
     */
    int insertSelective(PollQuestionResponse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utlzpollquestionresponse
     *
     * @mbggenerated Mon Sep 10 17:04:28 IST 2012
     */
    List<PollQuestionResponse> selectByExample(PollQuestionResponseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utlzpollquestionresponse
     *
     * @mbggenerated Mon Sep 10 17:04:28 IST 2012
     */
    PollQuestionResponse selectByPrimaryKey(Integer pollQuestionResponseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utlzpollquestionresponse
     *
     * @mbggenerated Mon Sep 10 17:04:28 IST 2012
     */
    int updateByExampleSelective(@Param("record") PollQuestionResponse record, @Param("example") PollQuestionResponseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utlzpollquestionresponse
     *
     * @mbggenerated Mon Sep 10 17:04:28 IST 2012
     */
    int updateByExample(@Param("record") PollQuestionResponse record, @Param("example") PollQuestionResponseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utlzpollquestionresponse
     *
     * @mbggenerated Mon Sep 10 17:04:28 IST 2012
     */
    int updateByPrimaryKeySelective(PollQuestionResponse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table utlzpollquestionresponse
     *
     * @mbggenerated Mon Sep 10 17:04:28 IST 2012
     */
    int updateByPrimaryKey(PollQuestionResponse record);
}