package com.ziksana.domain.polls;

public class PollTracker extends PollTrackerKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utlzpolltracker.alreadyVoted
     *
     * @mbggenerated Mon Sep 10 17:04:28 IST 2012
     */
    private Boolean alreadyVoted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utlzpolltracker.alreadyVoted
     *
     * @return the value of utlzpolltracker.alreadyVoted
     *
     * @mbggenerated Mon Sep 10 17:04:28 IST 2012
     */
    public Boolean getAlreadyVoted() {
        return alreadyVoted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utlzpolltracker.alreadyVoted
     *
     * @param alreadyVoted the value for utlzpolltracker.alreadyVoted
     *
     * @mbggenerated Mon Sep 10 17:04:28 IST 2012
     */
    public void setAlreadyVoted(Boolean alreadyVoted) {
        this.alreadyVoted = alreadyVoted;
    }
}