package com.ziksana.domain.polls;

import java.util.Date;

public class Poll {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utlzpoll.ID
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    private Integer ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utlzpoll.PollStartDate
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    private Date pollStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utlzpoll.PollEndDate
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    private Date pollEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utlzpoll.PollType
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    private Integer pollType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utlzpoll.PollVisibility
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    private Integer pollVisibility;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utlzpoll.Active
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    private Boolean active;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utlzpoll.TotalResponses
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    private Integer totalResponses;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utlzpoll.ID
     *
     * @return the value of utlzpoll.ID
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    public Integer getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utlzpoll.ID
     *
     * @param ID the value for utlzpoll.ID
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    public void setID(Integer ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utlzpoll.PollStartDate
     *
     * @return the value of utlzpoll.PollStartDate
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    public Date getPollStartDate() {
        return pollStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utlzpoll.PollStartDate
     *
     * @param pollStartDate the value for utlzpoll.PollStartDate
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    public void setPollStartDate(Date pollStartDate) {
        this.pollStartDate = pollStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utlzpoll.PollEndDate
     *
     * @return the value of utlzpoll.PollEndDate
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    public Date getPollEndDate() {
        return pollEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utlzpoll.PollEndDate
     *
     * @param pollEndDate the value for utlzpoll.PollEndDate
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    public void setPollEndDate(Date pollEndDate) {
        this.pollEndDate = pollEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utlzpoll.PollType
     *
     * @return the value of utlzpoll.PollType
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    public Integer getPollType() {
        return pollType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utlzpoll.PollType
     *
     * @param pollType the value for utlzpoll.PollType
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    public void setPollType(Integer pollType) {
        this.pollType = pollType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utlzpoll.PollVisibility
     *
     * @return the value of utlzpoll.PollVisibility
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    public Integer getPollVisibility() {
        return pollVisibility;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utlzpoll.PollVisibility
     *
     * @param pollVisibility the value for utlzpoll.PollVisibility
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    public void setPollVisibility(Integer pollVisibility) {
        this.pollVisibility = pollVisibility;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utlzpoll.Active
     *
     * @return the value of utlzpoll.Active
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    public Boolean getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utlzpoll.Active
     *
     * @param active the value for utlzpoll.Active
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    public void setActive(Boolean active) {
        this.active = active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utlzpoll.TotalResponses
     *
     * @return the value of utlzpoll.TotalResponses
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    public Integer getTotalResponses() {
        return totalResponses;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utlzpoll.TotalResponses
     *
     * @param totalResponses the value for utlzpoll.TotalResponses
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    public void setTotalResponses(Integer totalResponses) {
        this.totalResponses = totalResponses;
    }
}