package com.ziksana.domain.polls;

public class PollQuestion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utlzpollquestion.ID
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    private Integer ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utlzpollquestion.Active
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    private Boolean active;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utlzpollquestion.QuestionText
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    private String questionText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utlzpollquestion.Answer1
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    private String answer1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utlzpollquestion.Answer2
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    private String answer2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utlzpollquestion.Answer3
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    private String answer3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utlzpollquestion.Answer4
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    private String answer4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utlzpollquestion.Answer5
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    private String answer5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utlzpollquestion.ID
     *
     * @return the value of utlzpollquestion.ID
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    public Integer getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utlzpollquestion.ID
     *
     * @param ID the value for utlzpollquestion.ID
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    public void setID(Integer ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utlzpollquestion.Active
     *
     * @return the value of utlzpollquestion.Active
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    public Boolean getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utlzpollquestion.Active
     *
     * @param active the value for utlzpollquestion.Active
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    public void setActive(Boolean active) {
        this.active = active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utlzpollquestion.QuestionText
     *
     * @return the value of utlzpollquestion.QuestionText
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    public String getQuestionText() {
        return questionText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utlzpollquestion.QuestionText
     *
     * @param questionText the value for utlzpollquestion.QuestionText
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    public void setQuestionText(String questionText) {
        this.questionText = questionText == null ? null : questionText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utlzpollquestion.Answer1
     *
     * @return the value of utlzpollquestion.Answer1
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    public String getAnswer1() {
        return answer1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utlzpollquestion.Answer1
     *
     * @param answer1 the value for utlzpollquestion.Answer1
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    public void setAnswer1(String answer1) {
        this.answer1 = answer1 == null ? null : answer1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utlzpollquestion.Answer2
     *
     * @return the value of utlzpollquestion.Answer2
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    public String getAnswer2() {
        return answer2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utlzpollquestion.Answer2
     *
     * @param answer2 the value for utlzpollquestion.Answer2
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    public void setAnswer2(String answer2) {
        this.answer2 = answer2 == null ? null : answer2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utlzpollquestion.Answer3
     *
     * @return the value of utlzpollquestion.Answer3
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    public String getAnswer3() {
        return answer3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utlzpollquestion.Answer3
     *
     * @param answer3 the value for utlzpollquestion.Answer3
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    public void setAnswer3(String answer3) {
        this.answer3 = answer3 == null ? null : answer3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utlzpollquestion.Answer4
     *
     * @return the value of utlzpollquestion.Answer4
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    public String getAnswer4() {
        return answer4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utlzpollquestion.Answer4
     *
     * @param answer4 the value for utlzpollquestion.Answer4
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    public void setAnswer4(String answer4) {
        this.answer4 = answer4 == null ? null : answer4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utlzpollquestion.Answer5
     *
     * @return the value of utlzpollquestion.Answer5
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    public String getAnswer5() {
        return answer5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utlzpollquestion.Answer5
     *
     * @param answer5 the value for utlzpollquestion.Answer5
     *
     * @mbggenerated Tue Sep 18 18:56:18 IST 2012
     */
    public void setAnswer5(String answer5) {
        this.answer5 = answer5 == null ? null : answer5.trim();
    }
}